// Config from https://github.com/johndavedecano/node-rtmp-hls/blob/master/src/config.js
import { resolve } from 'path'

const config = {
  rtmp: {
    port: 1935,
    chunk_size: 60000,
    gop_cache: false,
    ping: 30,
    ping_timeout: 60,
  },
  http: {
    port: 8000,
    allow_origin: '*',
    mediaroot: process.env.MEDIA_ROOT || resolve(__dirname, '..', 'media'),
  },
  relay: {
    ffmpeg: process.env.FFMPEG_PATH || '/usr/local/bin/ffmpeg',
    tasks: [
      {
        app: 'stream',
        mode: 'push',
        edge: 'rtmp://127.0.0.1/hls_1080p',
      },
      {
        app: 'stream',
        mode: 'push',
        edge: 'rtmp://127.0.0.1/hls_720p',
      },
      {
        app: 'stream',
        mode: 'push',
        edge: 'rtmp://127.0.0.1/hls_480p',
      },
      {
        app: 'stream',
        mode: 'push',
        edge: 'rtmp://127.0.0.1/hls_360p',
      },
    ],
  },
  trans: {
    ffmpeg: process.env.FFMPEG_PATH || '/usr/local/bin/ffmpeg',
    tasks: [
      {
        app: 'hls_1080p',
        hls: true,
        ac: 'aac',
        acParam: ['-b:a', '192k', '-ar', 48000],
        vc: 'libx264',
        vcParam: [
          '-g',
          '60',
          '-vf',
          'scale=1920:-2',
          '-b:v',
          '5000k',
          '-preset',
          'veryfast',
          '-profile:v',
          'baseline',
          '-bufsize',
          '7500k',
        ],
        hlsFlags: '[hls_time=10:hls_list_size=0:hls_flags=delete_segments]',
      },
      {
        app: 'hls_720p',
        hls: true,
        ac: 'aac',
        acParam: ['-b:a', '128k', '-ar', 48000],
        vc: 'libx264',
        vcParam: [
          '-g',
          '60',
          '-vf',
          'scale=1280:-2',
          '-b:v',
          '2800k',
          '-preset',
          'veryfast',
          '-profile:v',
          'baseline',
          '-bufsize',
          '4200k',
        ],
        hlsFlags: '[hls_time=10:hls_list_size=0:hls_flags=delete_segments]',
      },
      {
        app: 'hls_480p',
        hls: true,
        ac: 'aac',
        acParam: ['-b:a', '128k', '-ar', 48000],
        vc: 'libx264',
        vcParam: [
          '-g',
          '60',
          '-vf',
          'scale=854:-2',
          '-b:v',
          '1400k',
          '-preset',
          'veryfast',
          '-profile:v',
          'baseline',
          '-bufsize',
          '2100k',
        ],
        hlsFlags: '[hls_time=10:hls_list_size=0:hls_flags=delete_segments]',
      },
      {
        app: 'hls_360p',
        hls: true,
        ac: 'aac',
        acParam: ['-b:a', '96k', '-ar', 48000],
        vc: 'libx264',
        vcParam: [
          '-g',
          '60',
          '-vf',
          'scale=480:-2',
          '-b:v',
          '800k',
          '-preset',
          'veryfast',
          '-profile:v',
          'baseline',
          '-bufsize',
          '1200k',
        ],
        hlsFlags: '[hls_time=10:hls_list_size=0:hls_flags=delete_segments]',
      },
    ],
  },
}

export default config
