services:
  builder:
    image: builder
    build: .
  api:
    build: ./api
    container_name: api
    ports:
      - "5000:5000"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "/build/api/firebase.json"
    restart: always
  web:
    build: ./web
    container_name: web
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - api
  stream:
    build: ./stream
    container_name: stream
    ports:
      - "8000:8000"
      - "1935:1935"
    depends_on:
      - api
    restart: always
    environment:
      FFMPEG_PATH: "/usr/local/bin/ffmpeg"
      MEDIA_ROOT: "/build/stream/media"
