services:
  builder:
    image: builder
    build: .
  api:
    build:
      context: ./api
      args:
        NODE_ENV: production
    container_name: api
    ports:
      - 5000:5000
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /build/api/firebase.json
      NODE_ENV: production
    restart: always
  web:
    build:
      context: ./web
      args:
        NODE_ENV: production
    container_name: web
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - api
    environment:
      NODE_ENV: production
  stream:
    build:
      context: ./stream
      args:
        NODE_ENV: production
    container_name: stream
    ports:
      - 8000:8000
      - 1936:1935
    depends_on:
      - api
    restart: always
    environment:
      FFMPEG_PATH: /usr/local/bin/ffmpeg
      MEDIA_ROOT: /build/stream/media
      NODE_ENV: production
