POST http://localhost:5000/register
Content-Type: application/json

{
  "username": "jonah",
  "password": "test1234"
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
  "username": "jonah",
  "password": "test1234"
}

###

GET http://localhost:5000/logout

###